JSAB2-73 Menu is wired
green-fox-academy/jsa-bloodstone-app pull request #28
Opened 2019-12-13 06:20 UTC by GuJialu

2019-12-13 09:18 UTC, HanqingZ approved these changes

2019-12-13 09:40 UTC, HONGTAO-T approved these changes

2019-12-13 09:45 UTC, kyya approved these changes

2019-12-13 09:45 UTC, Kyya commented on frontend/src/MainView/index.jsx
> +const MainViewstyle = {
I think only components can be start with upercase.

2019-12-13 09:53 UTC, evasimonyi requested changes

2019-12-13 09:53 UTC, evasimonyi commented on frontend/src/MainView/index.jsx
> +const MainViewstyle = {
lowecase please

2019-12-13 09:53 UTC, evasimonyi commented on frontend/src/MainView/index.jsx
> +      throw new Error('invalid currentlyDisplayComponent');
do you want to show this to the user? please return with a component which says 'Sorry, something went wrong' or something, but don't throw an error here

2019-12-16 01:52 UTC, kyya approved these changes

2019-12-16 01:52 UTC, HONGTAO-T approved these changes

2019-12-16 01:58 UTC, evasimonyi approved these changes

2019-12-16 01:58 UTC, merged