JSAB2-96 Connect resource front end to back end
green-fox-academy/jsa-bloodstone-app pull request #36
Opened 2019-12-18 08:31 UTC by GuJialu

2019-12-18 10:01 UTC, HONGTAO-T approved these changes

2019-12-18 10:02 UTC, HanqingZ approved these changes

2019-12-19 04:41 UTC, evasimonyi requested changes
Right now the calculations and the resource updating is in the reducer, so there is no communication with the backend, only for the first time when you are fetching the mocked resources —> this way the frontend is not in sync with the backend. On the backend we wouldn’t store the actual amount. Right now everything is happening on the frontend, but the task says exactly the opposite: to connect the frontend to the backend.

Please refactor your code, and put the whole logic and calculations to the backend, and just communicate with the backend, dispatching an action from the frontend in every minute is perfect. 

I know you tried this solution for optimizing the performance, but sometimes it can not be more important than maintainability and testability. Also right now our goal is to practice as much as you can, and the HTTP communication is a crucial part in every application.

2019-12-19 04:41 UTC, evasimonyi commented on frontend/src/Resources/index.jsx
> +      <Text>{`Oops, ${error.message}`}</Text>
@GuJialu you said you'll handle this when connection the frontend to the backend
from the action creator you are sending back the status code as the payload when there's an error, so the user will see the status code here? please check

2019-12-19 06:36 UTC, GuJialu commented on frontend/src/Resources/index.jsx
> +      <Text>{`Oops, ${error.message}`}</Text>
I think the error will eventually be send to the error page as a prop, and then the error page will decided what to show to the user depend on the error. Currently it is just showing the error handling is working.

2019-12-19 07:20 UTC, HONGTAO-T approved these changes

2019-12-19 07:42 UTC, HanqingZ approved these changes

2019-12-19 08:19 UTC, HanqingZ approved these changes

2019-12-19 09:41 UTC, kyya approved these changes

2019-12-19 10:26 UTC, evasimonyi requested changes
you had 2 typos, if you fix them, I'll merge, no need for reviews again, if you don't modify anything else:)
also you can accept these here

2019-12-19 10:26 UTC, evasimonyi commented on backend/routers/resources.js
> +  const caulatedResources = {
```suggestion
  const calculatedResources = {
```

2019-12-19 10:26 UTC, evasimonyi commented on backend/routers/resources.js
> +  return res.status(200).send(caulatedResources);
```suggestion
  return res.status(200).send(calculatedResources);
```

2019-12-19 10:45 UTC, evasimonyi approved these changes

2019-12-19 10:45 UTC, merged