JSAB2-89 Forgetten password
green-fox-academy/jsa-bloodstone-app pull request #39
Opened 2019-12-20 07:17 UTC by HanqingZ

- add a forgetten password page
- User can enter whether username or email to find back their password

2019-12-20 07:19 UTC, HanqingZ commented
Please use the branch JSAB2-89-forgotten-page-test to test
This branch create a button link to the forgotten password page

2019-12-20 07:33 UTC, kyya requested changes

2019-12-20 07:33 UTC, Kyya commented on frontend/src/Login/actionCreator.js
> +      type: FORGOTPASSWORD,
please add underscore between FORGOT and PASSWORD.

2019-12-20 07:33 UTC, Kyya commented on frontend/src/Login/authReducer.js
> +    case FORGOTPASSWORD:
please add underscore between FORGOT and PASSWORD.

2019-12-20 07:48 UTC, GuJialu approved these changes

2019-12-23 02:13 UTC, kyya requested changes

2019-12-23 02:13 UTC, Kyya commented on frontend/src/Login/actionCreator.js
> +  if (input.includes('@')) {
If I have an email called '@@@@@@@@@', then what will happen?

2019-12-23 02:13 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +            placeholder="input"
I think our users may not know what data should input.
placeholder name could be username or email.

2019-12-24 10:02 UTC, HanqingZ commented
Since I add a verification using the regular expression, I have to ignore the lint for this part

2019-12-24 12:58 UTC, HONGTAO-T approved these changes

2019-12-25 09:20 UTC, hongtaoTang commented on frontend/src/Login/SubmitButton.jsx
> +import Icon from 'react-native-vector-icons/Entypo';
```
import { Ionicons } from '@expo/vector-icons';
```

2019-12-25 09:21 UTC, hongtaoTang commented on frontend/src/Login/SubmitButton.jsx
>        />
```
    <Ionicons
      name="ios-arrow-round-forward"
      color="#fff"
      size={32}
    />
```

2019-12-25 09:21 UTC, hongtaoTang commented on frontend/src/Login/ForgottenPassword.jsx
> +            <View style={{ transform: [{ rotate: '180deg' }] }}>
```
<View style={{ transform: [{ rotateY: '180deg' }] }}>
```

2019-12-25 09:22 UTC, HONGTAO-T approved these changes

2019-12-25 10:23 UTC, GuJialu approved these changes

2019-12-25 15:19 UTC, kyya approved these changes

2019-12-25 15:19 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +  }
If it is not related to the rendering process, I suggest moving it out of this `ForgottenPassword` function.

2019-12-25 15:19 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +    if (!validation(input) && USERNAME_BLACKLIST.indexOf(input.toLowerCase()) !== -1) {
We can use es6 ways.
```suggestion
    if (!validation(input) && USERNAME_BLACKLIST.includes(input.toLowerCase())) {
```

2020-01-04 14:45 UTC, evasimonyi approved these changes
very nice! 👍

2020-01-04 14:49 UTC, merged