JSAB2-91 Notifications
green-fox-academy/jsa-bloodstone-app pull request #43
Opened 2019-12-23 03:12 UTC by Kyya

2019-12-23 03:24 UTC, HanqingZ commented on backend/routers/users.js
> +      // .then((receipts) => {
plz delete comments

2019-12-23 11:49 UTC, HanqingZ approved these changes

2019-12-23 11:54 UTC, HONGTAO-T approved these changes

2019-12-29 03:13 UTC, GuJialu approved these changes

2020-01-06 05:32 UTC, evasimonyi requested changes

2020-01-06 05:32 UTC, evasimonyi commented on frontend/src/Notification/register.js
> +  });
add a catch branch please!
(unhandled promise rejection error!)

2020-01-07 01:29 UTC, HanqingZ approved these changes

2020-01-07 03:00 UTC, GuJialu approved these changes

2020-01-07 03:07 UTC, HONGTAO-T approved these changes

2020-01-07 05:26 UTC, evasimonyi approved these changes
💯  wow!!! :)

2020-01-07 05:26 UTC, merged