JSAB2-25 Registration frontend
green-fox-academy/jsa-bloodstone-app pull request #48
Opened 2019-12-26 07:51 UTC by HanqingZ

- add registration page with a simple verification for email and a blacklist for username
- PLEASE use the branch JSAB2-25-registration-frontend-test for testing

2019-12-26 08:11 UTC, GuJialu requested changes
Still need password length check and mocked map page.

2019-12-26 09:01 UTC, GuJialu approved these changes

2019-12-26 09:14 UTC, GuJialu approved these changes

2019-12-26 13:48 UTC, Kyya commented
Something has been checked in JSAB2-90, Login page addition.

2019-12-26 13:49 UTC, kyya approved these changes

2019-12-27 04:45 UTC, GuJialu approved these changes

2019-12-29 06:57 UTC, kyya approved these changes

2020-01-05 13:40 UTC, evasimonyi requested changes

2020-01-05 13:40 UTC, evasimonyi commented on frontend/src/Registration/index.jsx
> +    return navigation.navigate('Map');
this part doesn't work for me, neither on Android or on iPhone, I just get a warning about the successful registration, but it doesn't redirect me to the mocked Map page, is it working on a simulator or tablet? can you please check it?

2020-01-06 01:51 UTC, HONGTAO-T approved these changes

2020-01-06 01:51 UTC, kyya approved these changes

2020-01-06 04:05 UTC, evasimonyi approved these changes
👍 💯

2020-01-06 04:05 UTC, merged