JSAB2-90, Login page addition
green-fox-academy/jsa-bloodstone-app pull request #50
Opened 2019-12-26 09:15 UTC by HanqingZ

- create two links on Login page for Registration page and Forgotten Password page

2019-12-26 13:36 UTC, kyya requested changes

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +          <View style={styles.button}>
```suggestion
          <View style={styles.buttonContainer}>
```

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +  button: {
```suggestion
  buttonContainer: {
```

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Login/ForgottenPassword.jsx
> +            </View>
I have a more elegant solution for it.
You can add a `direction` prop to SubmitButton which can specify the direction of the arrow icon.

```jsx
 <Ionicons
  name={`ios-arrow-round-${direction}`}
  color="#fff"
  size={36}
/>
```
and it's prop type can be enum type.
```js
SubmitButton.propTypes = {
  direction: PropType.oneOf(['back', 'forward']),
};
```
and the usage is
```jsx
<SubmitButton direction="forward" onPress={handleSubmit} />
```

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Registration/index.jsx
> +import { InputField, SubmitButton } from '../common/components';
Try to leave more empty lines here.

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Registration/index.jsx
> +      );
it can be one line
```jsx
return <ActivityIndicator size="large" color={Colors.tealColor} />;
```

2019-12-26 13:36 UTC, Kyya commented on frontend/src/Map/index.jsx
> +    <View style={[styles.screenStyle,
There is no screen style anymore, consider to use `styles.container` instead.

2019-12-27 06:38 UTC, GuJialu approved these changes

2019-12-27 06:55 UTC, kyya approved these changes

2020-01-03 07:41 UTC, GuJialu approved these changes

2020-01-06 10:02 UTC, kyya approved these changes

2020-01-06 10:03 UTC, GuJialu approved these changes

2020-01-06 10:23 UTC, evasimonyi requested changes
if you delete the comment, I'll merge, no need for CR :)

2020-01-06 10:23 UTC, evasimonyi commented on frontend/src/Registration/index.jsx
> +    // width: 300,
```suggestion
```

2020-01-06 12:29 UTC, evasimonyi approved these changes

2020-01-06 12:29 UTC, merged