JSAB2-135 Connect buildings frontend to backend
green-fox-academy/jsa-bloodstone-app pull request #82
Opened 2020-01-13 10:27 UTC by hongtaoTang

connect buildings frontend to backend

2020-01-13 14:10 UTC, kyya approved these changes

2020-01-13 14:10 UTC, Kyya commented on frontend/src/Buildings/actionCreator.js
> +    fetch(URL, {
```suggestion
    return fetch(URL, {
```

2020-01-13 14:15 UTC, HanqingZ approved these changes

2020-01-14 05:16 UTC, evasimonyi requested changes
- not sure if we want to display these kind of messages to the user:
"throw new Error(`Can not find upgrading time rules about level ${level}`);", it's rather for the developer, the user cannot fix this error. It's ok now, but in the future we should keep in mind what to display to the user

- please keep the `isVisible` naming everywhere for this, because its value is a boolean

- is it on purpose that the container takes the whole width if there is only one building in the last row? I think it should have the same container as the others, just be put into the center

![IMG_20200114_130958](https://user-images.githubusercontent.com/30794349/72316039-cf2a2f80-36cf-11ea-9607-5ce6e3be684a.jpg)

-

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/Buildings/buildingItem.jsx
> +            <Text style={styles.levelStyle}>{`Lv.${level}`}</Text>
```suggestion
            <Text style={styles.levelStyle}>{`Lvl ${level}`}</Text>
```

Lvl is the semi-official abbreviation for level:)

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/common/components/Popup.jsx
> +function Popup({ visible, onPress, children }) {
```suggestion
function Popup({ isVisible, onPress, children }) {
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/Buildings/actionCreator.js
> +        'Content-Type': 'application/json',
```suggestion
```

in a GET request you shouldn't set this header, because there is no content that you send

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/OneBuilding/index.jsx
> +  onClickClose, targetBuildingId, visible,
```suggestion
  onClickClose, targetBuildingId, isVisible,
```

it's a boolean, please rename

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/OneBuilding/index.jsx
> +  if (!visible) {
```suggestion
  if (!isVisible) {
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/OneBuilding/index.jsx
> +    <Popup onPress={onClickClose} visible={visible}>
```suggestion
    <Popup onPress={onClickClose} visible={isVisible}>
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/OneBuilding/index.jsx
> +  visible: PropTypes.bool,
```suggestion
  isVisible: PropTypes.bool,
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/OneBuilding/index.jsx
> +  visible: false,
```suggestion
  isVisible: false,
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/common/components/Popup.jsx
> +      visible={visible}
```suggestion
      visible={isVisible}
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/common/components/Popup.jsx
> +  visible: PropTypes.bool,
```suggestion
  isVisible: PropTypes.bool,
```

2020-01-14 05:16 UTC, evasimonyi commented on frontend/src/common/components/Popup.jsx
> +  visible: false,
```suggestion
  isVisible: false,
```

2020-01-14 07:02 UTC, kyya approved these changes

2020-01-14 07:02 UTC, GuJialu approved these changes

2020-01-14 07:10 UTC, evasimonyi approved these changes

2020-01-14 07:10 UTC, merged