JSAB2-134 Connect troops frontend to backend
green-fox-academy/jsa-bloodstone-app pull request #83
Opened 2020-01-13 12:29 UTC by hongtaoTang

connect troops frontend to backend

2020-01-13 14:56 UTC, HanqingZ commented on frontend/src/Troops/actionCreator.js
> +    fetch(URL, {
`return fetch(URL, {`

2020-01-13 14:57 UTC, kyya approved these changes

2020-01-13 14:57 UTC, HanqingZ approved these changes

2020-01-14 09:39 UTC, evasimonyi requested changes
only one minor change is needed

2020-01-14 09:39 UTC, evasimonyi commented on frontend/src/Troops/TroopLevel.jsx
> +          <Text style={styles.cardText}>{`Level ${level}: ${count} Troops`}</Text>
please check the count
- if it's 1, it should say Troop (so `1 Troop`)
- if it's more than 1, it should say Troops (so for example `3 Troops`)

2020-01-14 10:20 UTC, kyya approved these changes

2020-01-14 11:19 UTC, HanqingZ approved these changes

2020-01-15 03:10 UTC, GuJialu approved these changes

2020-01-15 03:11 UTC, evasimonyi approved these changes

2020-01-15 03:11 UTC, merged