JSAB2-50 Battle map backend
green-fox-academy/jsa-bloodstone-app pull request #86
Opened 2020-01-14 07:46 UTC by GuJialu

2020-01-14 08:22 UTC, HONGTAO-T approved these changes

2020-01-14 08:31 UTC, HanqingZ approved these changes

2020-01-14 12:57 UTC, kyya approved these changes

2020-01-15 03:00 UTC, HanqingZ approved these changes

2020-01-15 03:00 UTC, HONGTAO-T approved these changes

2020-01-15 03:30 UTC, evasimonyi requested changes
please change the naming of `usersInPlanet` to `usersOnPlanet`, cause it's grammatically incorrect:) thank you

very nice job!

2020-01-15 03:30 UTC, evasimonyi commented on backend/routers/battle.js
> +async function getUsersInPlanet(req, res, next) {
```suggestion
async function getUsersOnPlanet(req, res, next) {
```

2020-01-15 03:30 UTC, evasimonyi commented on backend/routers/battle.js
> +    const usersInPlanet = await UserModel.find(
```suggestion
    const usersOnPlanet = await UserModel.find(
```

2020-01-15 03:30 UTC, evasimonyi commented on backend/routers/battle.js
> +    const usersInPlanetFiltered = await Promise.all(usersInPlanet.map(async (element) => {
```suggestion
    const usersOnPlanetFiltered = await Promise.all(usersOnPlanet.map(async (element) => {
```

2020-01-15 03:30 UTC, evasimonyi commented on backend/routers/battle.js
> +    res.send({ usersInPlanet: usersInPlanetFiltered });
```suggestion
    res.send({ usersOnPlanet: usersOnPlanetFiltered });
```

2020-01-15 03:30 UTC, evasimonyi commented on backend/routers/battle.js
> +router.get('/planet/:planet', auth, getUsersInPlanet);
```suggestion
router.get('/planet/:planet', auth, getUsersOnPlanet);
```

:planet: name or id?

2020-01-15 03:33 UTC, GuJialu commented on backend/routers/battle.js
> +router.get('/planet/:planet', auth, getUsersInPlanet);
It's the name

2020-01-15 04:05 UTC, evasimonyi approved these changes

2020-01-15 04:05 UTC, merged