JSAB2-15 Academy
green-fox-academy/jsa-bloodstone-app pull request #92
Opened 2020-01-15 11:23 UTC by hongtaoTang

when you click on your academy, you will see a popup. Click on the create troop button, you will receive a notification on your phone and your level 1 troop will increase by 1.

2020-01-15 11:24 UTC, kyya approved these changes

2020-01-15 11:30 UTC, HanqingZ approved these changes

2020-01-15 14:53 UTC, evasimonyi requested changes

2020-01-15 14:53 UTC, evasimonyi commented on backend/routers/troops.js
> +    const purchase = await ResourceModel.purchaseItem(owner, cost);
```suggestion
    const hasEnoughMoney = await ResourceModel.purchaseItem(owner, cost);
```

purchase is not describing what you are checking

2020-01-15 14:53 UTC, evasimonyi commented on frontend/src/Troops/actionCreator.js
> +    return fetch(`${URL}?level=${level}`, {
```suggestion
    return fetch(`${URL}/?level=${level}`, {
```

2020-01-15 14:53 UTC, evasimonyi commented on frontend/src/Troops/actionCreator.js
> +    return fetch(`${URL}?level=${level}`, {
did it work for you this way without the `/`?

2020-01-15 14:53 UTC, evasimonyi commented on frontend/src/Troops/index.jsx
> +  } = listOfTroops;
it's rather details of troops and not an actual list, isn't it? as I see it's not the troops but the information about them so the name is confusing

2020-01-15 15:40 UTC, kyya requested changes

2020-01-15 15:40 UTC, Kyya commented on frontend/src/Troops/index.jsx
> +  if (isLoading || Object.keys(infoOfTroops.length === 0)) {
```suggestion
  if (isLoading || Object.keys(infoOfTroops).length === 0) {
```

2020-01-16 02:12 UTC, HanqingZ approved these changes

2020-01-16 02:13 UTC, GuJialu approved these changes

2020-01-16 02:13 UTC, kyya approved these changes

2020-01-16 02:27 UTC, evasimonyi requested changes

2020-01-16 02:27 UTC, evasimonyi commented on backend/routers/troops.js
> +    const hasEnoughMoney = await ResourceModel.purchaseItem(owner, cost);
```suggestion
    const hasEnoughMoney = await ResourceModel.purchaseItem(owner, cost);
```

don't have `purchaseItem` method anymore, please rebase

2020-01-16 02:33 UTC, HanqingZ approved these changes

2020-01-16 02:34 UTC, kyya approved these changes

2020-01-16 02:40 UTC, evasimonyi approved these changes

2020-01-16 02:40 UTC, merged